services:
  - type: web
    name: xcelerate2026-backend
    env: python
    region: oregon
    buildCommand: ./render-build.sh
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
